version: '3.7'

services:
  woocommerce: &woocommerce
    build: &build
      context: .
      args:
        version: "6.4.3"
        wc_version: "8.5.2"
    user: "33:33"
    ports:
      - 80:80
    depends_on:
      - mysql
    volumes:
      - /var/www/html
      - ./wc-bepaid-erip-payments:/var/www/html/wp-content/plugins/wc-bepaid-erip-payments
      - ./docker/src/languages:/var/www/html/wp-content/languages
    networks:
      - default
    environment:
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: root
      NODE_OPTIONS: "--openssl-legacy-provider"

  mysql:
    image: mysql:5.6
    networks:
      - default
    volumes:
      - /var/lib/mysql
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: root
