version: '3.7'

services:
  woocommerce: &woocommerce
    build: &build
      context: .
      args:
        version: "5.4.2"
        wc_version: "4.3.1"
    ports:
      - 80:80
    depends_on:
      - mysql
    volumes:
      - /var/www/html
      - ./woocommerce-erip-payments:/var/www/html/wp-content/plugins/woocommerce-erip-payments
      - ./docker/src/languages:/var/www/html/wp-content/languages
    networks:
      - default
    environment:
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_HOST: mysql

  mysql:
    image: mysql:5.6
    networks:
      - default
    volumes:
      - /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
